import { NavBar } from "@/components/NavBar";

// This app has no landing page of its own — it's entered via a tokenized
// /report/[token] URL generated by the upstream intake/payment flow (a separate app).
export default function RootPage() {
  return (
    <div style={{ minHeight: "100vh" }}>
      <NavBar tag="Quick-Start Blueprint Report Generator" />
      <main style={{ maxWidth: 480, margin: "0 auto", padding: "140px 24px", textAlign: "center" }}>
        <div style={{ fontSize: 20, fontWeight: 700, marginBottom: 12 }}>Nothing to see here</div>
        <p style={{ fontSize: 14, color: "var(--text-secondary)", lineHeight: 1.6 }}>
          Reports are accessed via a tokenized link sent after your Quick-Start Blueprint scan completes.
        </p>
      </main>
    </div>
  );
}
